# Generated by Django 5.2.1 on 2025-06-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_gitcommand_language_alter_gitlesson_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlesson',
            name='steps',
            field=models.JSONField(default=list, help_text='Список шагов урока в формате массива объектов'),
        ),
        migrations.AlterField(
            model_name='gitquiz',
            name='choices',
            field=models.JSONField(help_text='Список вариантов ответа (JSON-массив)'),
        ),
        migrations.DeleteModel(
            name='GitLessonStep',
        ),
    ]
